/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include"stdio.h"
#include"STM32F103C8.h"
#include"RCC.h"
#include"GPIO.h"
#include"ISR.h"
#include"USART.h"
#include"SPI.h"
#include"I2C.h"
#include"TIMER.h"
#include"LCD.h"
#include"Keypad.h"
#include "Seven_Segment.h"

/******************************************************************************
*                               	Defines			                          *
*******************************************************************************/
#define RCC_BASE_1			(Peripherals_Base + 0x00021000UL)
#define RCC_APB2ENR_1		*(volatile uint32_t *)(RCC_BASE_1 + 0x18)
#define RCC_CFGR_1		*(volatile uint32_t *)(RCC_BASE_1 + 0x04)


void clock_init()
{
	RCC_CFGR_1 |= (0b100 << 8 );

	RCC_CFGR_1 |= (0b101 << 11 );
}



/************************************************************************************/
void RCC_init()
{
	MCAL_RCC_GetSYS_CLCKFreq(RCC_8MHZ);
	MCAL_RCC_GetHCLKFreq();
	MCAL_RCC_GetPCLK1Freq();
	MCAL_RCC_GetPCLK2Freq();
	MCAL_RCC_Peripherals_enable(APB2, RCC_AFIO, RCC_Enable);
	MCAL_RCC_Peripherals_enable(APB2, RCC_GPIOA, RCC_Enable);
	MCAL_RCC_Peripherals_enable(APB2, RCC_GPIOB, RCC_Enable);
}

void GPIO_init(void)
{
	MCAL_GPIO_Init(GPIOA, PIN0, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN1, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN2, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN3, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN4, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN5, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN6, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN7, Output_PP_Mode_Speed10MHZ);
}


int main(void)
{

	clock_init();

	while(1)
	{

	}
}
