/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include"stdio.h"
#include"STM32F103C8.h"
#include"RCC.h"
#include"GPIO.h"
#include"ISR.h"
#include"USART.h"
#include"SPI.h"
#include"I2C.h"
#include"TIMER.h"
#include"LCD.h"
#include"Keypad.h"
#include "Seven_Segment.h"

/******************************************************************************
*                               	Defines			                          *
*******************************************************************************/
typedef volatile unsigned int vuint32_t;
#define GPIOA_BASE_1		 0x40010800
#define GPIOA_CRH 		*(volatile uint32_t *)(GPIOA_BASE_1 + 0x04)
#define GPIOA_ODR 		*(volatile uint32_t *)(GPIOA_BASE_1 + 0x0C)

#define RCC_BASE_1			(Peripherals_Base + 0x00021000UL)
#define RCC_APB2ENR_1		*(volatile uint32_t *)(RCC_BASE_1 + 0x18)
void x(int c)
{
	for(int i = 0 ; i < c ; i++)
	{
		for(int j = 0 ; j < 255 ; j++);
	}
}





/************************************************************************************/
void RCC_init()
{
	MCAL_RCC_GetSYS_CLCKFreq(RCC_8MHZ);
	MCAL_RCC_GetHCLKFreq();
	MCAL_RCC_GetPCLK1Freq();
	MCAL_RCC_GetPCLK2Freq();
	MCAL_RCC_Peripherals_enable(APB2, RCC_AFIO, RCC_Enable);
	MCAL_RCC_Peripherals_enable(APB2, RCC_GPIOA, RCC_Enable);
	MCAL_RCC_Peripherals_enable(APB2, RCC_GPIOB, RCC_Enable);
}

void GPIO_init(void)
{
	MCAL_GPIO_Init(GPIOA, PIN0, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN1, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN2, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN3, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN4, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN5, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN6, Output_PP_Mode_Speed10MHZ);
	MCAL_GPIO_Init(GPIOA, PIN7, Output_PP_Mode_Speed10MHZ);
}


int main(void)
{
	//Enable IO port A clock
	RCC_APB2ENR_1 |= 1<<2 ;

	//InitGPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for(int i = 0; i < 5000; i++); // arbitrary delay
		GPIOA_ODR &= ~(1<<13) ;
		for(int i = 0; i < 5000; i++);

	}
}
