/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*****************
 *   Includes    *
 ****************/
#include "driver.h"
#include "Main_Algorithm.h"
#include "Pressure_Sensor_Driver.h"
#include "Alarm_Minitor.h"

/******************************************************************/

int main(void)
{
	App_init();

    while(1)
    {
    	High_Pressure_detection_system_APP();
    	Delay(250000);
    }
}
